spring:
  application:
    name: ai-chatbot-saas

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiry: 86400000

groq:
  base-url: https://api.groq.com/openai/v1
  model: llama3-8b-8192
  api-key: ${GROQ_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info