spring:
  application:
    name: ai-chatbot-saas

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: riyaN@05
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: update
    show-sql: false

  flyway:
    enabled: true

server:
  port: 8081

jwt:
  secret: 2mSzRlG+kZeIee1BMluHGqUgtKT2ywlZ2pMlY5dG6HZxPpTjxZ84Rf5vyYh0TU8G
  expiry: 86400000

ollama:
  base-url: ${OLLAMA_BASE_URL:http://ollama:11434}
  model: ${OLLAMA_MODEL:qwen2.5:1.5b}

management:
  endpoints:
    web:
      exposure:
        include: health, info